#pragma once
#include "../../resource.h"
#include "../../Debug_sys/Debug_sys.h"
#include "../main_header.h"
#include "../lib_struct.h"
#include "../../Str_to_double/str_to_double.h"
#include "../../Str_to_double/char_change.h"
#include "../../Integrate/Simps_meth.h"
#include "../../Plotting.h"
